"""empty message

Revision ID: 2b0bc16cda83
Revises: f858836fbdd9
Create Date: 2023-04-25 18:23:44.894786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0bc16cda83'
down_revision = 'f858836fbdd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav__people', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('id_people',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_constraint('fav__people_id_people_key', type_='unique')
        batch_op.drop_constraint('fav__people_id_user_key', type_='unique')
        batch_op.create_foreign_key(None, 'people', ['id_people'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['id_user'], ['id'])

    with op.batch_alter_table('fav__planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_planets', sa.Integer(), nullable=True))
        batch_op.alter_column('id_user',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_constraint('fav__planets_id_people_key', type_='unique')
        batch_op.drop_constraint('fav__planets_id_user_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['id_user'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['id_planets'], ['id'])
        batch_op.drop_column('id_people')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav__planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_people', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('fav__planets_id_user_key', ['id_user'])
        batch_op.create_unique_constraint('fav__planets_id_people_key', ['id_people'])
        batch_op.alter_column('id_user',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('id_planets')

    with op.batch_alter_table('fav__people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('fav__people_id_user_key', ['id_user'])
        batch_op.create_unique_constraint('fav__people_id_people_key', ['id_people'])
        batch_op.alter_column('id_people',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('id_user',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
