"""empty message

Revision ID: f858836fbdd9
Revises: 0442627ee739
Create Date: 2023-04-25 17:01:21.291373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f858836fbdd9'
down_revision = '0442627ee739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav__people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('id_people', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['id_people'])
        batch_op.create_unique_constraint(None, ['id_user'])
        batch_op.drop_column('name')

    with op.batch_alter_table('fav__planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('id_people', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['id_user'])
        batch_op.create_unique_constraint(None, ['id_people'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav__planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id_people')
        batch_op.drop_column('id_user')

    with op.batch_alter_table('fav__people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id_people')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###
